#!/usr/bin/env bash
# This script that displays
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
n=0
while [ $n ]
do
echo "To infinity and beyond"
sleep 2
done
