#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with FizzBuzz
# Using a for loop
for ((i=1; i<=100; i++))
do
# Check if its a multiple of both 3 and 5
if ((i % 3 == 0)) && ((i % 5 == 0)); then
echo "FizzBuzz"
# Check if its a multiple of 3
elif ((i % 3 == 0)); then
echo "Fizz"
# Check if its a multiple of 5
elif ((i % 5 == 0)); then
echo "Buzz"
else
echo "$i"
fi
done
