#!/usr/bin/env bash
# This script that loops from 1 to 10 and
# Displays loops according to iterations
n=1
#  Usig while loop, if, elif and else statements
while [ $n -le 10 ]
do
if [ $n -eq 4 ]
then
echo "bad luck"
elif [ $n -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
# Incremnt
n=$((n + 1))
done
