#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes
# It displays hours from 0 to 12, and minutes from 1 to 59
hour=0
minute=1
# Using the while loop
while [ $hour -le 12 ]
do
echo "Hour: $hour"
while [ $minute -le 59 ]
do
echo "$minute"
minute=$((minute + 1))
done
# Increment
minute=1
hour=$((hour + 1))
done | head -n 70
