#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Using the for loop
for file in *
do
echo "#file" | cut -f 2- -d '-'
done
